# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Gregory Ashton
tagline:
url:
paginate:         3
baseurl:          /
author:
  name:           Gregory Ashton
  url:
  email:

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/ga7g08/ga7g08.github.io

# Conversions
highlighter: pygments

# Markdown Processors
maruku:
  use_tex:    false
  use_divs:   false
  png_engine: blahtex
  png_dir:    images/latex
  png_url:    /images/latex
  fenced_code_blocks: true

markdown: kramdown
