# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Gregory Ashton
tagline:
url:
paginate:         3
baseurl:          /
author:
  name:           Gregory Ashton
  url:
  email:

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/ga7g08/ga7g08.github.io

# Conversions
highliter: pygments
