site_name: Gregory Ashton
site_url: http://www.GregoryAshton.github.io
site_author: Gregory Ashton
site_dir: ../docs/
repo_url: https://github.com/GregoryAshton/GregoryAshton.github.io
nav:
    - Home: index.md
    - Science: science.md
    - Projects: projects.md
    - Notes: notes.md
theme: material
markdown_extensions:
    - attr_list
